import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/introduction',
        'getting-started/installation',
        'getting-started/quickstart',
      ],
    },
    {
      type: 'category',
      label: 'Account & Security',
      link: {
        type: 'doc',
        id: 'account-security/index', 
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'account-security', 
        },
      ],
    },
    {
      type: 'category',
      label: 'Use of CoinByte ',
      link: {
        type: 'doc',
        id: 'user-guide/index', 
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'user-guide', 
        },
      ],
    },
    {
      type: 'category',
      label: 'Deposits and Withdrawals',
      link: {
        type: 'doc',
        id: 'deposits-withdrawals/index', 
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'deposits-withdrawals', 
        },
      ],
    },
    {
      type: 'category',
      label: 'Trading',
      link: {
        type: 'doc',
        id: 'trading/index', 
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'trading', 
        },
      ],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [
        'troubleshooting/common-issues',
        'troubleshooting/advanced',
        'troubleshooting/contact-support',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Guides',
      items: [
        'advanced/customization',
        'advanced/integration',
        'advanced/security',
        'advanced/api-usage',
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
